//Modelo de llamadas automatizadas
using System;

namespace SCIABackendDemo.Models
{
    public class ScheduledCall
    {
        public int Id { get; set; }
        public string CallId { get; set; } = null!;
        public string PhoneNumber { get; set; } = null!;
        public DateTime ScheduledDate { get; set; }
        public bool Triggered { get; set; } = false;
        public bool AutoGenerated { get; set; } = false;
        public int UserId { get; set; }
    }
}
